### ISSUE TITLE
the server span's timestamp has set null，in zipkin ui,the server's serviceName cannot be searched

### ISSUE THREAD

**Issue by zengzonghou** [openzipkin/brave#365] opened 2017-03-15 09:00 UTC
in the class "com.github.kristofa.brave.Recorder",there is a segment code as follows:

```java
@Override void flush(Span span) {
      // In the RPC span model, the client owns the timestamp and duration of the span. If we
      // were propagated an id, we can assume that we shouldn't report timestamp or duration,
      // rather let the client do that. Worst case we were propagated an unreported ID and
      // Zipkin backfills timestamp and duration.
      synchronized (span) {
        if (InternalSpan.instance.context(span).shared) {
          for (int i = 0, length = span.getAnnotations().size(); i < length; i++) {
            if (span.getAnnotations().get(i).value.equals(Constants.SERVER_RECV)) {
              span.setTimestamp(null);
              break;
            }
          }
        }
      }
      reporter().report(toZipkin(span));
    }
  }
```

so in the server span, the timestamp and timestamp_millis is null, in the storage elasticsearch ,the data is that:
```json
{
  "timestamp_millis": 1489562030762,
  "traceId": "d9047dd85b716257",
  "id": "12ab39f405102c74",
  "name": "ibuildingopenservice.getbuildingdetail",
  "parentId": "d9047dd85b716257",
  "timestamp": 1489562030762914,
  "duration": 574812,
  "annotations": [
    {
      "timestamp": 1489562030762914,
      "value": "cs",
      "endpoint": {
        "serviceName": "broker-service",
        "ipv4": "192.168.249.59"
      }
    },
    {
      "timestamp": 1489562031337726,
      "value": "cr",
      "endpoint": {
        "serviceName": "broker-service",
        "ipv4": "192.168.249.59"
      }
    }
  ]
}
```

and 

```json
{
  "traceId": "d9047dd85b716257",
  "id": "12ab39f405102c74",
  "name": "ibuildingopenservice.getbuildingdetail",
  "parentId": "d9047dd85b716257",
  "duration": 571011,
  "annotations": [
    {
      "timestamp": 1489562031792358,
      "value": "sr",
      "endpoint": {
        "serviceName": "topsales",
        "ipv4": "192.168.249.48"
      }
    },
    {
      "timestamp": 1489562032363369,
      "value": "ss",
      "endpoint": {
        "serviceName": "topsales",
        "ipv4": "192.168.249.48"
      }
    }
  ]
}
```

the search query from zipkin server is that:

```json
{
  "size": 10,
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "timestamp_millis": {
                  "from": 1489562012256,
                  "to": 1489565612256,
                  "include_lower": true,
                  "include_upper": true
                }
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "nested": {
                      "query": {
                        "term": {
                          "annotations.endpoint.serviceName": "topsales"
                        }
                      },
                      "path": "annotations"
                    }
                  },
                  {
                    "nested": {
                      "query": {
                        "term": {
                          "binaryAnnotations.endpoint.serviceName": "topsales"
                        }
                      },
                      "path": "binaryAnnotations"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  },
  "aggregations": {
    "traceId_agg": {
      "terms": {
        "field": "traceId",
        "size": 1,
        "order": {
          "sort_agg": "desc"
        }
      },
      "aggregations": {
        "sort_agg": {
          "max": {
            "field": "timestamp_millis"
          }
        }
      }
    }
  }
}
```

if the server span field "timestamp_millis" is null, it can not be searched,
but we usually want to search by the server's serviceName,
how can i solve this problem? thanks

**Comment by zengzonghou** [comment] 2017-03-15 09:03
sorry,the format is a little confusion

**Comment by adriancole** [comment] 2017-03-15 11:16
ps I reformatted based on markdown syntax. you can click edit on your description to see how.

**Comment by adriancole** [comment] 2017-03-15 11:25
the server-side json showing duration looks like a bug in brave. can you reproduce it in a unit test? maybe where we are setting timestamp to null we should also set duration to null I think.

the other topic (how elasticsearch works wrt timestamp_millis) is not really brave related, so you can open an issue on zipkin about this (how queries work with timestamp and also service name). It might be something you can reproduce by adding a test to zipkin's SpanStoreTest.

**Comment by adriancole** [comment] 2017-05-11 03:37
This is fixed in latest zipkin. you did find a bug

**Closed by adriancole** 2017-05-11 03:37 UTC

**Comment by neicunlideyu** [comment] 2017-09-21 09:15
@adriancole still has this bug,
![image](https://user-images.githubusercontent.com/2801654/30688334-78a23da6-9e83-11e7-9c9d-47915f32a5dd.png)

**Comment by adriancole** [comment] 2017-09-21 11:02
If you dont mind please update to latest zipkin server and brave (using
Tracing.spanReporter to employ v2 format which is the same as Elasticsearch)

The shared flag is described in zipkin2.Span.shared javadoc and also the api
http://zipkin.io/zipkin-api/#/

Basically it means the server reuses (shares) the same span ID as the
client.

**Comment by neicunlideyu** [comment] 2017-10-11 03:53
@adriancole how to use v1 format and add timestamp, duration to span?

**Comment by adriancole** [comment] 2017-10-11 04:12
@neicunlideyu when a span is shared, you shouldn't re-add timestamp and duration (in v1 format). Why are you asking to? https://github.com/openzipkin/openzipkin.github.io/issues/49

**Comment by neicunlideyu** [comment] 2017-10-11 05:33
@adriancole  I find that although some spans (root span on server side) is not shared, the timestamp and duration is still null. 

what's more, how to tell whether a span is shared? By the spanid passed from client?

**Comment by adriancole** [comment] 2017-10-11 07:43
>
> @adriancole <https://github.com/adriancole> I find that although some
> spans (root span on server side) is not shared, the timestamp and duration
> is still null.
>
> what's more, how to tell whether a span is shared? By the spanid passed
> from client?
>
shared is when the server receives X-B3 headers which have X-B3-Sampled=1
Are you using most recent brave? Seems a bug if you are getting no
timestamp/duration on a root span.

**Comment by neicunlideyu** [comment] 2017-10-11 07:51
@adriancole yes, 4.7.1 version

**Comment by adriancole** [comment] 2017-10-11 07:56
if you are using recent zipkin server, you can use
Tracing.Builder.spanReporter which guarantees spans always include
timestamp/duration

if not, can you find an occurance where headers were not sent, yet the root
span had no timestamp/duration?

**Comment by neicunlideyu** [comment] 2017-10-11 10:19
@adriancole when the root span has a child client span using TracingHttpClientBuilder

**Comment by adriancole** [comment] 2017-10-11 10:39
@neicunlideyu PS which storage are you using? might be easier on https://gitter.im/openzipkin/zipkin

**Comment by adriancole** [comment] 2017-10-11 10:43
ps here is how you make reporter2 use v1 encoding (I think you asked earlier) https://github.com/openzipkin/zipkin-reporter-java#legacy-encoding

**Comment by adriancole** [comment] 2017-10-11 11:19
anyway I will put in a unit test to make sure when brave creates a not-shared server span, timestamp and duration are present when using v1 format (just to make sure).

**Comment by adriancole** [comment] 2017-10-11 14:16
@neicunlideyu I think you should use latest brave and reporter2. This will ensure any translation logic is correct.

Here's a test that shows regardless of server framework, a span is not shared when there are no incoming IDs: https://github.com/openzipkin/brave/commit/ae0477150000673cab1599fdb9b21dc958e4f2fa

Here's a test for the conversion library used by recent brave and reporter2, showing that root server spans (which aren't shared) end up converting to v1 spans with timestamp and duration:
https://github.com/openzipkin/zipkin/blob/master/zipkin/src/test/java/zipkin/internal/V2SpanConverterTest.java#L215

If you don't mind, update to latest things and try again!
