### ISSUE TITLE
how to trace one-way method in brave?

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/brave#340] opened 2017-01-17 03:44 UTC
i have some method is one-way  method, like kafka or thrift, i want to trace this one-way method by brave.

in kafka's producer or thrift's client, i send message in server A, and my code is 
```
clientTracer.startNewSpan(spanName);
clientTracer.setClientSent();

doSomeThing()

clientTracer.setClientReceived();
```

and i send traceid, spanid, parentid, sampled send to kafka's consumer or thrift's server in server B

and in server B
```
serverTracer.clearCurrentSpan();
serverTracer.setStateCurrentTrace(SpanId.builder().traceId(traceId).spanId(spanId).parentId(parentId).sampled(sampled).build(), spanName);
serverTracer.setServerReceived();

doSomeThing()

serverTracer.setServerSend();
```

in zipkin i found 
![image](https://cloud.githubusercontent.com/assets/1763935/22006932/f3447692-dca9-11e6-87c4-366be2383218.png)

and

![image](https://cloud.githubusercontent.com/assets/1763935/22006935/01ec90b2-dcaa-11e6-88be-4e88b07740b8.png)

i think in zipkin-ui only show client's span, not show server's span

i use brave 4, how should i use brave's api , it can both show client and server's api?

thanks!

**Comment by adriancole** [comment] 2017-01-17 03:47
brave 4 was designed for this. can you take a look at the example here:
https://github.com/openzipkin/brave/tree/master/brave/src/test/java/brave/features/async
there's another one here, too
https://gist.github.com/adriancole/76d94054b77e3be338bd75424ca8ba30

the important thing is that you are calling span.flush() after sending or receiving the one-way span

**Comment by dragontree101** [comment] 2017-01-17 04:57
thanks very much! 

in kafka producer, i only use `span.finsh()` and `clientTracer.setClientSent()` but i do not use `clientTracer.setClientReceived();` that is ok?

and in kafka consumer, my code is 
```
serverTracer.setServerReceived();
Span span = getServerSpan(tracer, brave.serverSpanThreadBinder());
span.finish();

doSomeThing()

serverTracer.setServerSend();
```
does i have need others?

**Comment by adriancole** [comment] 2017-01-17 08:48
I wouldn't attempt to model one-way span using ClientTracer and
ServerTracer, instead use the new brave.Tracer api as mentioned.

There's no flush capability in ClientTracer or ServerTracer, and what you
mentioned will add the wrong annotations to the span.

**Comment by dragontree101** [comment] 2017-01-17 09:07
now i use ClientTracer or ServerTracer and flush by mysql， i test kafka example， it looks is ok。

in client i use https://github.com/openzipkin/brave/blob/master/brave-core/src/test/java/com/github/kristofa/brave/example/TracerAdapterTest.java#L78

and server i use https://github.com/openzipkin/brave/blob/master/brave-core/src/test/java/com/github/kristofa/brave/example/TracerAdapterTest.java#L104

**Comment by adriancole** [comment] 2017-01-17 09:20
I can't see what you are doing as you don't paste your code. The tracer adapter wasn't meant to show how to do one-way spans, rather how to interop with the brave 3 api. I pasted two links beforehand showing how to do one-way spans with brave.Tracer.

If you are satisfied with your approach, then I suppose it is good enough for you. Just keep in mind I spend time answering and explaining in effort to save us both time in later bugs.

If you end up with a bug because you are using ClientTracer and ServerTracer which is not supported for one-way spans, please switch at that point to brave.Tracer as opposed to opening another issue. You can refer back to this issue and the two examples I gave.

 For now, sounds like you have what you want, so I'm closing.

**Closed by adriancole** 2017-01-17 09:20 UTC

**Comment by dragontree101** [comment] 2017-01-17 09:37
sorry, i should change use brave 4 api instead of  ClientTracer or ServerTracer to trace one way. 
thanks again.

**Comment by adriancole** [comment] 2017-01-17 09:39
yeah it would be very easy for me to help you in the future... plus it helps others in case you learn something in the process which doesn't work

**Comment by dragontree101** [comment] 2017-01-17 14:39
so i want to change my code from brave 3 api to brave 4 api ..

**Comment by adriancole** [comment] 2017-01-18 01:43
Ok, I've added another test that spells out exactly how to do one-way
including interop with Brave 3. Please join gitter
<https://gitter.im/openzipkin/zipkin> if you need further support.

https://github.com/openzipkin/brave/pull/343

**Comment by adriancole** [comment] 2017-06-30 12:37
for those interested in Kafka tracing, please see #211
